#!/usr/bin/env python

# Documentation of 'plotfile' see -
# http://matplotlib.org/api/pyplot_api.html#module-matplotlib.pyplot

# This script is used to plot the data generated by - 'test_airsea'

from pylab import plotfile, show, gca, savefig

fname="fort.400"
plotfile(fname, (0, 1, 2, 3), delimiter=' ',subplots=False)
gca().set_xlabel(r'Salinity')
gca().set_ylabel(r'Density (-1000 kg/m3)')
gca().set_title(r'Density as function of salinity')
savefig('rho_t=10.png')
show()

