#!/usr/bin/env python

# Documentation of 'plotfile' see -
# http://matplotlib.org/api/pyplot_api.html#module-matplotlib.pyplot

# This script is used to plot the data generated by - 'test_airsea'

from pylab import plotfile, show, gca, savefig

fname="fort.300"
plotfile(fname, (0, 1, 2, 3, 4, 5, 6), delimiter=' ',subplots=False)
gca().set_xlabel(r'Air sea temperature difference')
gca().set_ylabel(r'W/m2')
gca().set_title(r'Net longwave radiation')
savefig('longwave.png')
show()
