!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2_5972)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitgotm(f2pysetupfunc)
      use gotm, only : init_gotm
      use gotm, only : time_loop
      use gotm, only : clean_up
      external f2pysetupfunc
      call f2pysetupfunc(init_gotm,time_loop,clean_up)
      end subroutine f2pyinitgotm

      
      subroutine f2pyinittime(f2pysetupfunc)
      use time, only : maxn
      use time, only : minn
      external f2pysetupfunc
      call f2pysetupfunc(maxn,minn)
      end subroutine f2pyinittime

      
      subroutine f2pyinitgui_util(f2pysetupfunc)
      use gui_util, only : redirectoutput
      use gui_util, only : resetoutput
      use gui_util, only : getversion
      external f2pysetupfunc
      call f2pysetupfunc(redirectoutput,resetoutput,getversion)
      end subroutine f2pyinitgui_util

      subroutine f2py_bio_var_getdims_cc(r,s,f2pysetdata,flag)
      use bio_var, only: d => cc

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bio_var_getdims_cc
      subroutine f2py_bio_var_getdims_var_names(r,s,f2pysetdata,flag)
      use bio_var, only: d => var_names

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
         !s(r) must be equal to len(d(1))
      end if
      flag = 2
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bio_var_getdims_var_names
      subroutine f2py_bio_var_getdims_var_long(r,s,f2pysetdata,flag)
      use bio_var, only: d => var_long

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
         !s(r) must be equal to len(d(1))
      end if
      flag = 2
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bio_var_getdims_var_long
      subroutine f2py_bio_var_getdims_var_units(r,s,f2pysetdata,flag)
      use bio_var, only: d => var_units

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
         !s(r) must be equal to len(d(1))
      end if
      flag = 2
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bio_var_getdims_var_units
      
      subroutine f2pyinitbio_var(f2pysetupfunc)
      use bio_var, only : cc
      use bio_var, only : var_names
      use bio_var, only : var_long
      use bio_var, only : var_units
      external f2pysetupfunc
      external f2py_bio_var_getdims_cc
      external f2py_bio_var_getdims_var_names
      external f2py_bio_var_getdims_var_long
      external f2py_bio_var_getdims_var_units
      call f2pysetupfunc(f2py_bio_var_getdims_cc,f2py_bio_var_getdims_va&
     &r_names,f2py_bio_var_getdims_var_long,f2py_bio_var_getdims_var_uni&
     &ts)
      end subroutine f2pyinitbio_var

      subroutine f2py_meanflow_getdims_h(r,s,f2pysetdata,flag)
      use meanflow, only: d => h

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_meanflow_getdims_h
      
      subroutine f2pyinitmeanflow(f2pysetupfunc)
      use meanflow, only : h
      external f2pysetupfunc
      external f2py_meanflow_getdims_h
      call f2pysetupfunc(f2py_meanflow_getdims_h)
      end subroutine f2pyinitmeanflow


