//
// $Id: gotmmodule.c,v 1.1 2006-11-24 15:52:14 kbk Exp $
//
/* File: gotmmodule.c
 * This file is auto-generated with f2py (version:2_2236).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Mon Sep 11 10:52:14 2006
 * $Revision: 1.1 $
 * $Date: 2006-11-24 15:52:14 $
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *gotm_error;
static PyObject *gotm_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*need_cfuncs*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* init_gotm *********************************/
static char doc_f2py_rout_gotm_gotm_init_gotm[] = "\
Function signature:\n\
  init_gotm()\n\
";
/*  */
static PyObject *f2py_rout_gotm_gotm_init_gotm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "|:gotm.gotm.init_gotm",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of init_gotm ******************************/

/********************************* time_loop *********************************/
static char doc_f2py_rout_gotm_gotm_time_loop[] = "\
Function signature:\n\
  time_loop()\n\
";
/*  */
static PyObject *f2py_rout_gotm_gotm_time_loop(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "|:gotm.gotm.time_loop",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
Py_BEGIN_ALLOW_THREADS
/*callfortranroutine*/
        (*f2py_func)();
Py_END_ALLOW_THREADS
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of time_loop ******************************/

/********************************** clean_up **********************************/
static char doc_f2py_rout_gotm_gotm_clean_up[] = "\
Function signature:\n\
  clean_up()\n\
";
/*  */
static PyObject *f2py_rout_gotm_gotm_clean_up(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "|:gotm.gotm.clean_up",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of clean_up ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_time_def[] = {
  {"maxn",0,{{-1}},PyArray_INT},
  {"minn",0,{{-1}},PyArray_INT},
  {NULL}
};

static void f2py_setup_time(char *maxn,char *minn) {
  int i_f2py=0;
  f2py_time_def[i_f2py++].data = maxn;
  f2py_time_def[i_f2py++].data = minn;
}
extern void F_FUNC(f2pyinittime,F2PYINITTIME)(void (*)(char*,char*));
static void f2py_init_time(void) {
  F_FUNC(f2pyinittime,F2PYINITTIME)(f2py_setup_time);
}


static FortranDataDef f2py_gotm_def[] = {
  {"init_gotm",-1,{{-1}},0,NULL,(void *)f2py_rout_gotm_gotm_init_gotm,doc_f2py_rout_gotm_gotm_init_gotm},
  {"time_loop",-1,{{-1}},0,NULL,(void *)f2py_rout_gotm_gotm_time_loop,doc_f2py_rout_gotm_gotm_time_loop},
  {"clean_up",-1,{{-1}},0,NULL,(void *)f2py_rout_gotm_gotm_clean_up,doc_f2py_rout_gotm_gotm_clean_up},
  {NULL}
};

static void f2py_setup_gotm(char *init_gotm,char *time_loop,char *clean_up) {
  int i_f2py=0;
  f2py_gotm_def[i_f2py++].data = init_gotm;
  f2py_gotm_def[i_f2py++].data = time_loop;
  f2py_gotm_def[i_f2py++].data = clean_up;
}
extern void F_FUNC(f2pyinitgotm,F2PYINITGOTM)(void (*)(char *,char *,char *));
static void f2py_init_gotm(void) {
  F_FUNC(f2pyinitgotm,F2PYINITGOTM)(f2py_setup_gotm);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

DL_EXPORT(int) initgotm(void) {
  int i;
  PyObject *m,*d, *s;
  m = gotm_module = Py_InitModule("gotm", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    Py_FatalError("can't initialize module gotm (failed to import numpy)");
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: 1.1 $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'gotm' is auto-generated with f2py (version:2_2236).\nFunctions:\n"
"Fortran 90/95 modules:\n""  time --- maxn,minn""  gotm --- init_gotm(),time_loop(),clean_up()"".");
  PyDict_SetItemString(d, "__doc__", s);
  gotm_error = PyErr_NewException ("gotm.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "time", PyFortranObject_New(f2py_time_def,f2py_init_time));
  PyDict_SetItemString(d, "gotm", PyFortranObject_New(f2py_gotm_def,f2py_init_gotm));
/*eof initf90modhooks*/

/*eof initcommonhooks*/

  if (PyErr_Occurred())
    return -1;

#ifdef F2PY_REPORT_ATEXIT
  on_exit(f2py_report_on_exit,(void*)"gotm");
#endif
return 0;
}
#ifdef __cplusplus
}
#endif
