!$Id: gotm-f2pywrappers2.F90,v 1.1 2006-11-24 15:52:14 kbk Exp $

!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2_2236)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitgotm(f2pysetupfunc)
#ifdef WINDOWS
      !DEC$ ATTRIBUTES DEFAULT :: f2pyinitgotm
#endif
      use gotm, only : init_gotm,time_loop,clean_up
      interface
        subroutine f2pysetupfunc(init_gotm,time_loop,clean_up)
#ifdef WINDOWS
          !DEC$ ATTRIBUTES DEFAULT :: f2pysetupfunc
#endif
          external init_gotm,time_loop,clean_up
        end subroutine f2pysetupfunc
      end interface
      !external f2pysetupfunc
      call f2pysetupfunc(init_gotm,time_loop,clean_up)
      
#ifdef WINDOWS
      ! Incredible but true: without the dummy calls below, IFORT 9.0.2713.2003
      ! believes init_gotm and time_loop to be "dead code", causing them to be
      ! eliminated from the library when optimizations are active...
      return
      call init_gotm
      call time_loop
#endif
      end subroutine f2pyinitgotm

      
      subroutine f2pyinittime(f2pysetupfunc)
#ifdef WINDOWS
      !DEC$ ATTRIBUTES DEFAULT :: f2pyinittime
#endif
      use time, only : maxn
      use time, only : minn
      interface
        subroutine f2pysetupfunc(maxn,minn)
#ifdef WINDOWS
          !DEC$ ATTRIBUTES DEFAULT :: f2pysetupfunc
#endif
          integer :: maxn,minn
        end subroutine f2pysetupfunc
      end interface
      !external f2pysetupfunc
      call f2pysetupfunc(maxn,minn)
      end subroutine f2pyinittime

      
      subroutine f2pyinitgui_util(f2pysetupfunc)
#ifdef WINDOWS
      !DEC$ ATTRIBUTES DEFAULT :: f2pyinitgui_util
#endif
      use gui_util, only : redirectoutput,resetoutput
      interface
        subroutine f2pysetupfunc(redirectoutput,resetoutput)
#ifdef WINDOWS
          !DEC$ ATTRIBUTES DEFAULT :: f2pysetupfunc
#endif
          external redirectoutput,resetoutput
        end subroutine f2pysetupfunc
      end interface
      !external f2pysetupfunc
      call f2pysetupfunc(redirectoutput,resetoutput)
      end subroutine f2pyinitgui_util
